### ISSUE TITLE
Error importing ENACT

### ISSUE THREAD

**Issue by alipirani88** [Sanofi-Public/enact-pipeline#10]
Have you come across this error? I was able to install it with pip but cannot import the enact libraries.

from enact.pipeline import ENACT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/enact/pipeline.py", line 10, in <module>
    import scanpy as sc
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/scanpy/__init__.py", line 16, in <module>
    from . import plotting as pl
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/scanpy/plotting/_utils.py", line 35, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by alipirani88** [comment]
Just realized that the pip install was incomplete:

Here is the pip installation error:

`(enact_v2) [apirani@ldragon5 ~]$ pip install enact-SO --no-cache-dir
Collecting enact-SO
  Downloading enact_SO-0.1.2-py3-none-any.whl.metadata (29 kB)
Collecting anndata==0.8.0 (from enact-SO)
  Downloading anndata-0.8.0-py3-none-any.whl.metadata (4.6 kB)
Collecting fastparquet==2024.5.0 (from enact-SO)
  Downloading fastparquet-2024.5.0.tar.gz (466 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting shapely==2.0.0 (from enact-SO)
  Downloading shapely-2.0.0.tar.gz (274 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting stardist==0.9.1 (from enact-SO)
  Downloading stardist-0.9.1.tar.gz (888 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 888.2/888.2 kB 232.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tifffile==2022.10.10 (from enact-SO)
  Downloading tifffile-2022.10.10-py3-none-any.whl.metadata (28 kB)
Collecting scvi-tools==1.0.3 (from enact-SO)
  Downloading scvi_tools-1.0.3-py3-none-any.whl.metadata (10 kB)
Collecting scanpy==1.9.1 (from enact-SO)
  Downloading scanpy-1.9.1-py3-none-any.whl.metadata (5.5 kB)
Collecting geopandas==0.12.2 (from enact-SO)
  Downloading geopandas-0.12.2-py3-none-any.whl.metadata (1.0 kB)
INFO: pip is looking at multiple versions of enact-so to determine which version is compatible with other requirements. This could take a while.
Collecting enact-SO
  Downloading enact_SO-0.1.1-py3-none-any.whl.metadata (29 kB)
Collecting anndata==0.10.8 (from enact-SO)
  Downloading anndata-0.10.8-py3-none-any.whl.metadata (6.6 kB)
Collecting shapely==2.0.5 (from enact-SO)
  Downloading shapely-2.0.5.tar.gz (282 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tifffile==2024.7.24 (from enact-SO)
  Downloading tifffile-2024.7.24-py3-none-any.whl.metadata (31 kB)
Collecting scvi-tools==1.1.6 (from enact-SO)
  Downloading scvi_tools-1.1.6-py3-none-any.whl.metadata (17 kB)
Collecting scanpy==1.10.2 (from enact-SO)
  Downloading scanpy-1.10.2-py3-none-any.whl.metadata (9.3 kB)
Collecting geopandas==1.0.1 (from enact-SO)
  Downloading geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)
Collecting enact-SO
  Downloading enact_SO-0.1-py3-none-any.whl.metadata (19 kB)
ERROR: Cannot install enact-so==0.1, enact-so==0.1.1 and enact-so==0.1.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    enact-so 0.1.2 depends on tensorflow==2.12.0
    enact-so 0.1.1 depends on tensorflow==2.17.0
    enact-so 0.1 depends on tensorflow==2.17.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by AlbertPlaPlanas** [comment]
It seems we have an issue in our 0.1.2 release. We'll fix it as soon as we can

On the meantime running `pip install enact-SO==0.1.1` should solve the issue.

**Comment by alipirani88** [comment]
pip install enact-SO==0.1.1 works for but I still get this error:

```
>>> from enact.pipeline import ENACT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rsrch5/home/neuro_rsrch/apirani/.conda/envs/enact_v3/lib/python3.9/site-packages/enact/pipeline.py", line 20, in <module>
    import scvi
  File "/rsrch5/home/neuro_rsrch/apirani/.conda/envs/enact_v3/lib/python3.9/site-packages/scvi/__init__.py", line 11, in <module>
    from . import data, model, external, utils
  File "/rsrch5/home/neuro_rsrch/apirani/.conda/envs/enact_v3/lib/python3.9/site-packages/scvi/model/__init__.py", line 2, in <module>
    from ._amortizedlda import AmortizedLDA
  File "/rsrch5/home/neuro_rsrch/apirani/.conda/envs/enact_v3/lib/python3.9/site-packages/scvi/model/_amortizedlda.py", line 15, in <module>
    from scvi.module import AmortizedLDAPyroModule
  File "/rsrch5/home/neuro_rsrch/apirani/.conda/envs/enact_v3/lib/python3.9/site-packages/scvi/module/__init__.py", line 1, in <module>
    from ._amortizedlda import AmortizedLDAPyroModule
  File "/rsrch5/home/neuro_rsrch/apirani/.conda/envs/enact_v3/lib/python3.9/site-packages/scvi/module/_amortizedlda.py", line 15, in <module>
    from scvi.module.base import PyroBaseModuleClass, auto_move_data
  File "/rsrch5/home/neuro_rsrch/apirani/.conda/envs/enact_v3/lib/python3.9/site-packages/scvi/module/base/__init__.py", line 1, in <module>
    from ._base_module import (
  File "/rsrch5/home/neuro_rsrch/apirani/.conda/envs/enact_v3/lib/python3.9/site-packages/scvi/module/base/_base_module.py", line 14, in <module>
    from flax.training import train_state
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/flax/training/train_state.py", line 17, in <module>
    import optax
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/optax/__init__.py", line 17, in <module>
    from optax import contrib
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/optax/contrib/__init__.py", line 17, in <module>
    from optax.contrib.cocob import cocob
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/optax/contrib/cocob.py", line 25, in <module>
    from optax._src import base
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/optax/_src/base.py", line 19, in <module>
    import chex
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/chex/_src/asserts_internal.py", line 34, in <module>
    from chex._src import pytypes
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/chex/_src/pytypes.py", line 53, in <module>
    Shape = jax.core.Shape
  File "/rsrch5/home/neuro_rsrch/apirani/.local/lib/python3.9/site-packages/jax/_src/deprecations.py", line 52, in getattr
    raise AttributeError(message)
AttributeError: jax.core.Shape is deprecated. Use Shape = Sequence[int | Any].
```

Here is the list of packages in the conda environment

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anndata                   0.10.8                   pypi_0    pypi
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
certifi                   2024.8.30                pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
enact-so                  0.1.1                    pypi_0    pypi
geopandas                 1.0.1                    pypi_0    pypi
idna                      3.10                     pypi_0    pypi
keras                     3.6.0                    pypi_0    pypi
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.47.0               hadc24fc_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
ml-dtypes                 0.4.1                    pypi_0    pypi
namex                     0.0.8                    pypi_0    pypi
ncurses                   6.5                  he02047a_1    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
optree                    0.13.0                   pypi_0    pypi
packaging                 24.2                     pypi_0    pypi
pip                       24.3.1             pyh8b19718_0    conda-forge
plotly                    5.24.0                   pypi_0    pypi
pyogrio                   0.10.0                   pypi_0    pypi
python                    3.9.20          h13acc7a_1_cpython    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.3                   pypi_0    pypi
scanpy                    1.10.2                   pypi_0    pypi
scvi-tools                1.1.6                    pypi_0    pypi
setuptools                75.3.0             pyhd8ed1ab_0    conda-forge
shapely                   2.0.5                    pypi_0    pypi
tensorboard               2.17.1                   pypi_0    pypi
tensorflow                2.17.0                   pypi_0    pypi
tifffile                  2024.7.24                pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toolz                     1.0.0                    pypi_0    pypi
tqdm                      4.67.0                   pypi_0    pypi
tzdata                    2024b                hc8b5060_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge

```

**Comment by AlbertPlaPlanas** [comment]
Unfortunately I am not able to reproduce your issue after running:

```
conda create -n enact011_p9 python=3.9
conda activate enact011_p9  
pip install enact-SO==0.1.1   
```
Nontheless, after running these operations I see we do have quite a different set of packages installed in our conda environments

[conda_env.txt](https://github.com/user-attachments/files/17679467/conda_env.txt)

**Comment by alipirani88** [comment]
OK - It seems the issue was with the dependencies already installed in my local directory and the pip install was using them instead. I ran it with  ```pip install enact-SO==0.1.1 --no-cache-dir``` 

Thanks you so much for helping me and keep us updated with the newer version. This is a huge effort putting together these tools for HD data analysis.

**Comment by AlbertPlaPlanas** [comment]
Good, we'll roll back to 0.1.1
